apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

commonLabels:
  project: jenkins

resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
